// Generated by scripts/build-english.py; edit translations, not this file.
'use strict';

// Static site: prepare an email, then let the visitor review and send it in their mail app.
const contactForm = document.querySelector('#contact-form');
const contactResult = document.querySelector('#contact-result');
const contactMailLink = document.querySelector('#contact-mail-link');
const contactCopyStatus = document.querySelector('#contact-copy-status');
let contactPreparedText = '';

function contactText(fr, ar) { return language === 'ar' ? ar : fr; }

contactForm.addEventListener('submit', event => {
  event.preventDefault();
  // Native constraints are supplemented with a whitespace check for free-text fields.
  for (const name of ['name', 'message']) {
    const field = contactForm.elements.namedItem(name);
    field.setCustomValidity(field.value.trim() ? '' : contactText('Please fill in this field.', 'يرجى تعبئة هذا الحقل.'));
  }
  if (!contactForm.reportValidity()) return;
  const data = new FormData(contactForm);
  const name = String(data.get('name')).trim();
  const email = String(data.get('email')).trim();
  const phone = String(data.get('phone')).trim();
  const subject = String(data.get('subject'));
  const message = String(data.get('message')).trim();
  const body = `${message}\n\n—\nName: ${name}\nEmail: ${email}${phone ? `\nPhone: ${phone}` : ''}`;
  contactMailLink.href = `mailto:${SITE_CONFIG.contactEmail}?subject=${encodeURIComponent(subject + ' — ' + name)}&body=${encodeURIComponent(body)}`;
  contactPreparedText = `To: ${SITE_CONFIG.contactEmail}\nSubject: ${subject} — ${name}\n\n${body}`;
  contactCopyStatus.textContent = '';
  contactResult.hidden = false;
  contactResult.focus({ preventScroll: true });
  contactResult.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block: 'nearest' });
});

contactForm.addEventListener('input', event => {
  if (event.target.setCustomValidity) event.target.setCustomValidity('');
  contactResult.hidden = true;
  contactPreparedText = '';
  contactCopyStatus.textContent = '';
});
contactForm.addEventListener('change', () => {
  contactResult.hidden = true;
  contactPreparedText = '';
});

document.querySelector('#contact-copy').addEventListener('click', async () => {
  if (!contactPreparedText) return;
  try {
    await navigator.clipboard.writeText(contactPreparedText);
    contactCopyStatus.textContent = contactText('Message copied. Paste it into your email app to send it.', 'تم نسخ الرسالة. ألصقوها في بريدكم الإلكتروني لإرسالها.');
  } catch {
    contactCopyStatus.textContent = contactText('Copying is unavailable. Use “Open my email app” or email us directly.', 'النسخ غير متاح. افتحوا تطبيق البريد أو راسلونا مباشرة.');
  }
});

const contactSubjectPresets = { press:'Interviews and press', collaboration:'Collaborations and partnerships', cinema:'Film or television project', event:'Event' };
const contactPreset = contactSubjectPresets[new URLSearchParams(location.search).get('subject')];
if (contactPreset) contactForm.elements.namedItem('subject').value = contactPreset;



document.addEventListener('site:languagechange', () => {
  const keys = { name:'contactName', email:'contactEmail', phone:'contactPhone', message:'contactMessage' };
  Object.entries(keys).forEach(([name,key]) => {
    const label = document.querySelector(`[data-i18n="${key}"]`);
    contactForm.elements.namedItem(name).placeholder = label.textContent;
  });
  contactCopyStatus.textContent = '';
});

document.querySelectorAll('[data-contact-info]').forEach(button => button.addEventListener('click', () => {
  const privacy = button.dataset.contactInfo === 'privacy';
  const title = privacy ? contactText('Privacy', 'الخصوصية') : contactText('About this website', 'معلومات الموقع');
  const copy = privacy
    ? contactText('Information entered in this form stays in your browser. It is not stored on this website or sent to a server. “Open my email app” passes the content to your email app; you then choose whether to send it. External websites, including Instagram, have their own privacy policies.', 'تبقى بيانات هذا النموذج في متصفحكم ولا تُحفظ أو تُرسل إلى خادم هذا الموقع. يفتح زر البريد المحتوى في تطبيق بريدكم، وتختارون بعد ذلك إرساله. للمواقع الخارجية، ومنها إنستغرام، سياسات خصوصية خاصة بها.')
    : contactText('This website presents Farah El Fassi’s work. For questions about content, photographs or usage rights, contact our team at the address below.', 'موقع تعريفي بفرح الفاسي. لأي استفسار عن المحتوى أو الصور أو حقوق استخدامها، يرجى التواصل مع فريقنا عبر البريد أدناه.');
  openContent(titleHTML('FARAH EL FASSI', title) + '<p>' + copy + '</p><p>' + contactHTML() + '</p>');
}));
