// Generated by scripts/build-english.py; edit translations, not this file.
'use strict';



const albumGrid = document.querySelector('.album-grid');
const albumPhotos = [...albumGrid.querySelectorAll('.album-photo')];
const albumFilters = [...document.querySelectorAll('[data-album-filter]')];
const albumSearch = document.querySelector('#album-query');
const albumSearchPanel = document.querySelector('#album-search-panel');
const albumSearchToggle = document.querySelector('.album-search-toggle');
const albumMoreButton = document.querySelector('#album-more');
const albumStatus = document.querySelector('#album-status');
const albumQuote = document.querySelector('.album-interlude');
let albumFilter = 'all';
let albumExpanded = false;
const normalizeAlbum = (text) => text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();

function updateAlbum() {
 const query = normalizeAlbum(albumSearch.value);
 const curated = albumFilter === 'all' && !query && !albumExpanded;
 albumGrid.classList.toggle('is-curated',curated);
 albumQuote.hidden = !curated;
 albumPhotos.forEach((photo) => {
  const categoryMatch = albumFilter === 'all' || photo.dataset.albumCategory === albumFilter;
  const textMatch = !query || normalizeAlbum(photo.dataset.search).includes(query);
  photo.hidden = !categoryMatch || !textMatch || (curated && photo.dataset.featured !== 'true');
 });
 const count = albumPhotos.filter((photo) => !photo.hidden).length;
 albumStatus.textContent = language === 'ar' ? count + ' صورة من ' + albumPhotos.length : count + ' photographs out of ' + albumPhotos.length;
 document.querySelector('.album-empty').hidden = count !== 0;
 document.querySelector('[data-gallery-expand]').disabled = count === 0;
 albumMoreButton.hidden = albumFilter !== 'all' || !!query;
 albumMoreButton.querySelector('span').textContent = language === 'ar' ? (albumExpanded ? AR.albumLess : AR.albumMore) : (albumExpanded ? 'BACK TO THE SELECTION' : 'VIEW ALL 34 PHOTOS');
 albumMoreButton.setAttribute('aria-expanded',String(albumExpanded));
 albumFilters.forEach((button) => button.setAttribute('aria-pressed',String(button.dataset.albumFilter === albumFilter)));
 currentImageIndex = 0;
}
albumFilters.forEach((button) => button.addEventListener('click',() => {
 albumFilter = button.dataset.albumFilter;
 updateAlbum();
}));
albumMoreButton.addEventListener('click',() => {
 albumExpanded = !albumExpanded;
 updateAlbum();
 document.querySelector('.album-toolbar').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});
});
albumSearchToggle.addEventListener('click',() => {
 const opening = albumSearchPanel.hidden;
 albumSearchPanel.hidden = !opening;
 albumSearchToggle.setAttribute('aria-expanded',String(opening));
 if (opening) albumSearch.focus();
 else { albumSearch.value=''; updateAlbum(); }
});
albumSearch.addEventListener('input',updateAlbum);
document.querySelector('#album-clear').addEventListener('click',() => { albumSearch.value=''; updateAlbum(); albumSearch.focus(); });
document.addEventListener('site:languagechange', () => {
 albumSearch.placeholder = language === 'ar' ? 'بورتريه، مراكش، كواليس…' : 'A portrait, Marrakech, a film set…';
 updateAlbum();
});

const rotatedPhotoObserver = new ResizeObserver((entries) => {
 for (const {target,contentRect} of entries) {
  const img=target.querySelector('img');
  img.style.width=contentRect.height+'px';
  img.style.height=contentRect.width+'px';
 }
});
albumPhotos.filter((photo)=>photo.dataset.rotation).forEach((photo)=>rotatedPhotoObserver.observe(photo));

document.querySelectorAll('[data-album-info]').forEach((button) => button.addEventListener('click',() => {
 const privacy=button.dataset.albumInfo==='privacy';
 openContent(titleHTML('FARAH EL FASSI',privacy?'Privacy':'About this website')+
  (privacy?'<p>No account is needed to browse this gallery. Search and filters run in your browser without sending your searches to a server. Social media and email links open external services governed by their own policies.</p>':'<p>This website presents Farah El Fassi’s artistic career. For images, interviews or information about the website, please contact our team.</p>')+
  '<p>'+contactHTML()+'</p>');
}));
updateAlbum();
