// Generated by scripts/build-english.py; edit translations, not this file.
'use strict';

const pressFilters = [...document.querySelectorAll('[data-press-filter]')];
const pressCards = [...document.querySelectorAll('[data-press-category]')];
const pressFilterStatus = document.querySelector('#press-filter-status');
const pressLoadMore = document.querySelector('#press-load-more');
const pressPageSize = 6;
let pressCurrentFilter = 'all';
let pressVisibleLimit = pressPageSize;

function renderPress() {
  const matches = pressCards.filter(card => pressCurrentFilter === 'all' || card.dataset.pressCategory.split(' ').includes(pressCurrentFilter));
  const visible = matches.slice(0, pressVisibleLimit);
  pressCards.forEach(card => { card.hidden = !visible.includes(card); });
  pressFilters.forEach(button => button.setAttribute('aria-pressed', String(button.dataset.pressFilter === pressCurrentFilter)));
  pressLoadMore.hidden = visible.length === matches.length;
  pressFilterStatus.textContent = language === 'ar'
    ? `${visible.length} من ${matches.length} مواد إعلامية`
    : `${visible.length} of ${matches.length} publications`;
}
pressFilters.forEach(button => button.addEventListener('click', () => {
  pressCurrentFilter = button.dataset.pressFilter;
  pressVisibleLimit = pressPageSize;
  renderPress();
}));
pressLoadMore.addEventListener('click', () => {
  const firstNewCard = pressCards.filter(card => card.hidden && (pressCurrentFilter === 'all' || card.dataset.pressCategory.split(' ').includes(pressCurrentFilter)))[0];
  pressVisibleLimit += pressPageSize;
  renderPress();
  // Continue keyboard reading at the first newly revealed publication.
  firstNewCard?.querySelector('a')?.focus({ preventScroll: true });
});
function updatePressDates() {
  const formatter = new Intl.DateTimeFormat(language === 'ar' ? 'ar-MA' : 'en-GB', { day:'numeric', month:'long', year:'numeric', timeZone:'UTC' });
  document.querySelectorAll('[data-press-date]').forEach(time => {
    time.textContent = formatter.format(new Date(time.dateTime + 'T12:00:00Z'));
  });
  document.querySelector('.press-filters').setAttribute('aria-label', language === 'ar' ? 'تصفية المواد الإعلامية' : 'Filter press coverage');
}


/* PRESS_TRANSLATIONS_START */

/* PRESS_TRANSLATIONS_END */

document.addEventListener('site:languagechange', () => { renderPress(); updatePressDates(); });
renderPress();
updatePressDates();
