// Generated by scripts/build-english.py; edit translations, not this file.
'use strict';

// A bounded intro, dismissible by keyboard, with no wait for remote assets.
(() => {
  const root = document.documentElement;
  const skip = document.querySelector('.cinema-skip');
  const shell = document.querySelector('.site-shell');
  if (!root.classList.contains('cinema-enter')) return;
  const motion = window.matchMedia('(prefers-reduced-motion: reduce)');
  let timer;
  const finish = () => {
    const hadFocus = document.activeElement === skip;
    root.classList.remove('cinema-enter');
    shell.inert = false;
    clearTimeout(timer);
    document.removeEventListener('keydown', onKey);
    motion.removeEventListener('change', finish);
    if (hadFocus) document.querySelector('.site-header .brand').focus({ preventScroll: true });
  };
  const onKey = (event) => { if (event.key === 'Escape' || event.key === 'Tab') finish(); };
  shell.inert = true;
  skip.addEventListener('click', finish, { once: true });
  document.addEventListener('keydown', onKey);
  motion.addEventListener('change', finish);
  timer = window.setTimeout(finish, 3400);
})();

/**
 * Configuration: connect only verified profiles and your own services.
 * Empty values deliberately show an honest placeholder instead of pretending
 * to send an email, play a video or link to an official social profile.
 */
const SITE_CONFIG = {
  contactEmail: 'contact@farahelfassi.com',
  showreelVideoUrl: '', // À renseigner à réception de la vidéo.
  social: {
    instagram: 'https://www.instagram.com/farahelfassi1/',
    facebook: 'https://www.facebook.com/Farah.Elfassi.Officiel/'
  }
};

const FILMS = {
  "rahma": {
    "title": "Rahma",
    "arabic": "رحمة",
    "year": 2025,
    "kind": "TV series",
    "director": "",
    "role": "Nadia",
    "summary": "To escape a destructive marriage, Rahma tries to rebuild her life. Farah El Fassi plays Nadia.",
    "dates": "2025 — first season listed by IMDb.",
    "sources": [
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt35950179/"
      }
    ],
    "image": "../assets/films/rahma.jpg",
    "meta": "2025 · TV series",
    "writer": "Bouchra Malak",
    "duration": "45 min per episode"
  },
  "quitte": {
    "title": "Quitte ou double",
    "arabic": "آخر اختيار",
    "year": 2024,
    "kind": "Feature film",
    "director": "Rachida Saadi",
    "summary": "Noura and Mehdi’s marriage is put to the test by Noura’s addiction to poker, amid debts, secrets and difficult choices.",
    "dates": "2024 — year listed by the production company and the National Film Festival.",
    "sources": [
      {
        "label": "Janaprod — production",
        "url": "https://www.janaprod.com/quitte-ou-double.html"
      },
      {
        "label": "National Film Festival",
        "url": "https://www.fnf.ma/detail_doc?id=OTQ3"
      },
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt35501341/"
      }
    ],
    "duration": "86 min",
    "cast": "Farah El Fassi, Mohamed Nadif, Youssef El Arabi, Rania Rabia",
    "image": "../assets/films/quitte.webp",
    "meta": "2024 · Feature film",
    "role": "Noura (Nora on IMDb)"
  },
  "bayn": {
    "title": "Bayn Al Qosour",
    "arabic": "بين القصور",
    "year": 2024,
    "kind": "TV series",
    "director": "Hicham El Jebbari",
    "summary": "Sakina returns to the neighbourhood where she grew up. Coming home forces her to confront her past and unsettles her family’s life.",
    "dates": "First broadcast: Ramadan 2024, on MBC5 and Shahid.",
    "sources": [
      {
        "label": "Cedars Art Production",
        "url": "https://sabbah.com/ar/details/743"
      },
      {
        "label": "Interview with the screenwriter — Le360",
        "url": "https://fr.le360.ma/culture/lidee-le-personnage-de-lqatorze-le-casting-la-scenariste-bouchra-malek-nous-dit-tout-sur-la-serie_ITAK245FDRBXHJEMLVDJFTSCXY/"
      },
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt32125685/"
      }
    ],
    "writer": "Bouchra Malek",
    "cast": "Mohamed Khouyi, Houda Rihani, Saadia Ladib, Aziz Hattab, Farah El Fassi",
    "image": "../assets/films/bayn.webp",
    "meta": "2024 · TV series",
    "role": "Warda"
  },
  "batal": {
    "title": "L’Batal",
    "arabic": "البطل",
    "year": 2024,
    "kind": "Feature film",
    "director": "Omar Lotfi",
    "role": "",
    "summary": "An amateur actor agrees to pose as a lover to cover for a friend. A disappearance turns his improvised role into a risky adventure.",
    "dates": "2024 — Moroccan release on 9 October, according to IMDb.",
    "sources": [
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt34741810/"
      },
      {
        "label": "Salé Film Festival — English title",
        "url": "https://fiffs.ma/en/cineaste-detail.php?id=MTM0&type=0"
      }
    ],
    "image": "../assets/films/batal.jpg",
    "meta": "2024 · Feature film",
    "duration": "102 min",
    "englishTitle": "The Hero",
    "englishTitleLabel": "English festival title"
  },
  "salamate": {
    "title": "Salamate et ses filles",
    "arabic": "سلمات أبو البنات",
    "year": 2021,
    "kind": "TV series",
    "director": "",
    "role": "",
    "summary": "A newly retired father discovers a different side of his three daughters’ everyday lives and the changes within his family.",
    "dates": "2021 — Farah’s participation as credited on IMDb. The series is listed there as running from 2020 to 2023; this period does not necessarily cover her full involvement.",
    "sources": [
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt13493180/"
      },
      {
        "label": "IMDb — English title",
        "url": "https://www.imdb.com/title/tt13493180/"
      }
    ],
    "image": "../assets/films/salamate.jpg",
    "meta": "2021 · TV series",
    "englishTitle": "Salamat and His Daughters",
    "englishTitleLabel": "English title"
  },
  "mora": {
    "title": "La Mora",
    "arabic": "لامورا",
    "year": 2020,
    "kind": "Feature film",
    "director": "Mohamed Ismaïl",
    "role": "Maria",
    "summary": "Through a letter from her mother, Rosa pieces together a family history spanning Spain and Morocco, marked by war.",
    "dates": "2020 — the year listed on IMDb and in the 2022 Salé Film Festival catalogue. IMDb also lists a Moroccan release on 24 September 2025.",
    "sources": [
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt10743088/"
      }
    ],
    "image": "../assets/films/mora-upload.jpg",
    "meta": "2020 · Feature film",
    "duration": "91 min"
  },
  "page": {
    "title": "La Première Page",
    "arabic": "الصفحة الأولى",
    "year": 2018,
    "kind": "TV series",
    "director": "Driss Roukhe",
    "summary": "The everyday lives of journalists seeking exclusive stories for their online outlet, exploring a range of social issues.",
    "dates": "Broadcast in 2018 on Al Aoula.",
    "sources": [
      {
        "label": "Interview with Farah El Fassi — Machahid",
        "url": "https://machahid.info/166756.html"
      },
      {
        "label": "Series overview — Alyaoum24",
        "url": "https://alyaoum24.com/1080977.html"
      }
    ],
    "role": "Fatiha",
    "image": "../assets/films/page.webp",
    "meta": "2018 · TV series"
  },
  "bahlawan": {
    "title": "Al-Bahlawan",
    "arabic": "البهلوان",
    "year": 2016,
    "kind": "TV film",
    "director": "Mohamed Chrif Tribak",
    "role": "Sanae",
    "summary": "Now married, Soufian meets Sanae, his former partner, again. The unexpected encounter upsets the balance of his life.",
    "dates": "2016 — TV film listed by IMDb.",
    "sources": [
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt28259265/"
      }
    ],
    "image": "../assets/films/bahlawan.jpg",
    "meta": "2016 · TV film",
    "duration": "85 min"
  },
  "espoirs": {
    "title": "Dés… Espoirs",
    "arabic": "إحباط",
    "year": 2015,
    "kind": "Feature film",
    "director": "Mohamed Ismail",
    "summary": "Amine, an architect shaped by a difficult childhood, sees his convictions and love life shaken by his encounter with Leïla.",
    "dates": "Production: 2015 according to the CCM. Moroccan theatrical release: 28 November 2018 according to Le Matin. IMDb lists 2016.",
    "sources": [
      {
        "label": "Moroccan Cinema Centre",
        "url": "https://www.ccm.ma/en/fiche_film-673"
      },
      {
        "label": "Le Matin — theatrical release",
        "url": "https://lematin.ma/cinema/maroc/film/des-espoirs"
      },
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt8871138/"
      },
      {
        "label": "Filmexport — English catalogue",
        "url": "https://www.filmexport.ma/en/longs-metrages/9_Des...-Espoirs"
      }
    ],
    "duration": "122 min (CCM listing)",
    "cast": "Omar Lotfi, Farah El Fassi, Fehd Benchemsi, Ibtissam Moustatir",
    "image": "../assets/films/espoirs.webp",
    "meta": "2015 · Feature film",
    "role": "Leïla",
    "englishTitle": "The...Hopes",
    "englishTitleLabel": "English catalogue title"
  },
  "bonheurs": {
    "title": "Petits bonheurs",
    "arabic": "أفراح صغيرة",
    "year": 2015,
    "kind": "Feature film",
    "director": "Mohamed Chrif Tribak",
    "summary": "In Tetouan, Noufissa and her mother find a home with Lalla Amina. A deep friendship develops between Noufissa and Fetouma, only to be tested by a secret engagement.",
    "dates": "2015 — year listed by the Moroccan Cinema Centre. IMDb lists 2016.",
    "sources": [
      {
        "label": "Moroccan Cinema Centre",
        "url": "https://www.ccm.ma/en/fiche_film.php?id=663"
      },
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt3644024/"
      },
      {
        "label": "Filmexport — English title",
        "url": "https://www.filmexport.ma/en/longs-metrages/37_Petits-Bonheurs"
      }
    ],
    "duration": "85 min",
    "cast": "Anissa Lanaya, Farah El Fassi, Maha Daoud, Fama Ferrah",
    "image": "../assets/films/bonheurs.webp",
    "meta": "2015 · Feature film",
    "role": "Chama",
    "englishTitle": "Small Pleasures",
    "englishTitleLabel": "English title"
  },
  "hibal": {
    "title": "Hibal Rih",
    "arabic": "حبال الريح",
    "year": 2015,
    "kind": "TV series",
    "director": "Driss Roukhe",
    "role": "",
    "summary": "A Moroccan series inspired by folk stories and myths.",
    "dates": "2015 — IMDb lists the first broadcast as 18 June. The CCM documents the production and Driss Roukhe’s direction.",
    "sources": [
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt37673381/"
      },
      {
        "label": "CCM — 2015 television productions",
        "url": "https://www.ccm.ma/download-file?filename=doc1_1157.pdf"
      }
    ],
    "image": "../assets/films/hibal.jpg",
    "meta": "2015 · TV series"
  },
  "coeur": {
    "title": "Cœur noyé",
    "arabic": "القلب الغارق",
    "year": 2014,
    "kind": "Feature film",
    "director": "Farid Lakkimi",
    "summary": "Inspector Medi questions Souad, the former assistant of painter Kamal. Her testimony retraces the tragic lives of the people she has known.",
    "dates": "Production: 2014 according to AlloCiné. Some filmographies list 2017; French VOD release: 23 November 2020. These dates refer to different records. IMDb lists the film as Drowned Heart in 2019.",
    "sources": [
      {
        "label": "AlloCiné — film details",
        "url": "https://www.allocine.fr/film/fichefilm_gen_cfilm%3D223773.html"
      },
      {
        "label": "Studio Eustache — sound mixing in 2017",
        "url": "https://www.studio-eustache.com/references"
      },
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt6838990/"
      },
      {
        "label": "Capuseen — English release",
        "url": "https://www.capuseen.com/films/7516-drowned-heart"
      }
    ],
    "duration": "100 min",
    "role": "Souad",
    "cast": "Farah El Fassi, Farid Regragui, Mohamed Badissy, Malek Akhmiss",
    "alternate": "../assets/films/coeur-en.webp",
    "international": "Drowned Heart",
    "image": "../assets/films/coeur.webp",
    "meta": "2014 · Feature film",
    "englishTitle": "Drowned Heart",
    "englishTitleLabel": "English title"
  },
  "boughaba": {
    "title": "Boughaba",
    "arabic": "بوغابة",
    "year": 2013,
    "kind": "TV film",
    "director": "Driss Roukhe",
    "role": "Yamna",
    "summary": "Bouazza, deeply attached to the forest where he lives, marries Yamna. A strange light phenomenon disrupts their everyday lives.",
    "dates": "2013 — TV film listed by IMDb.",
    "sources": [
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt3592238/"
      }
    ],
    "image": "../assets/films/boughaba-upload.jpg",
    "meta": "2013 · TV film"
  },
  "enfant": {
    "title": "L’Enfant cheikh",
    "arabic": "الطفل الشيخ",
    "year": 2012,
    "kind": "Feature film",
    "director": "Hamid Benani",
    "role": "",
    "summary": "A young man is torn between the occupying army and the resistance led by his uncle.",
    "dates": "2012 — the year listed on IMDb. Moroccan theatrical release: 7 September 2016.",
    "sources": [
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt2403407/"
      },
      {
        "label": "Le360 — 2016 theatrical release",
        "url": "https://fr.le360.ma/culture/video-lenfant-cheikh-de-hamid-bennani-enfin-au-cinema-le-7-septembre-81917/"
      },
      {
        "label": "IMDb — English alternative title",
        "url": "https://www.imdb.com/title/tt2403407/"
      }
    ],
    "image": "../assets/films/enfant.jpg",
    "meta": "2012 · Feature film",
    "duration": "80 min",
    "englishTitle": "The Child Sheikh",
    "englishTitleLabel": "English title"
  },
  "camarades": {
    "title": "Le Temps des camarades",
    "arabic": "زمن الرفاق",
    "year": 2009,
    "kind": "Feature film",
    "director": "Mohamed Chrif Tribak",
    "role": "Rahil",
    "summary": "In northern Morocco in the 1990s, Rahil chooses university despite her family’s opposition and discovers a campus divided by political tensions.",
    "dates": "Presented as early as 2008 according to the Salé Film Festival; IMDb lists 2009 and a Moroccan release on 29 April.",
    "sources": [
      {
        "label": "IMDb — project details",
        "url": "https://www.imdb.com/fr/title/tt1576420/"
      },
      {
        "label": "Salé Film Festival — Farah’s career",
        "url": "https://www.fiffs.ma/cineaste-detail.php?id=MTM0&type=0"
      },
      {
        "label": "Tetouan Film Festival — English title",
        "url": "https://festivaltetouan.org/colloque-rencontres-2021/"
      }
    ],
    "image": "../assets/films/camarades.jpg",
    "meta": "2009 · Feature film",
    "duration": "103 min",
    "englishTitle": "Time of Comrades",
    "englishTitleLabel": "English title"
  }
};

const AWARDS = [
  ['2026', 'Best African Actress', 'Africa Golden Awards'],
  ['2025', 'Tribute', 'Salé International Women’s Film Festival'],
  ['2024', 'Best Actress', 'Festival Écrans Noirs'],
  ['2022', 'Best Actress', 'Premios Lorca de Granada']
];

const AR = {};

const $ = (selector, parent = document) => parent.querySelector(selector);
const $$ = (selector, parent = document) => Array.from(parent.querySelectorAll(selector));
const escapeHTML = (value) => String(value).replace(/[&<>"']/g, (char) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
}[char]));
const contentDialog = $('#content-dialog');
const imageDialog = $('#image-dialog');
const dialogBody = $('#dialog-body');
const nav = $('#navigation');
const menuToggle = $('.menu-toggle');
const track = $('.gallery-track') || document;
const language = 'en';
let currentImageIndex = 0;
// HTML is already translated, including the content used by shared dialogs.
$$('[data-i18n]').forEach(element => { element.dataset.fr = element.innerHTML; });
document.addEventListener('DOMContentLoaded', () => {
  document.dispatchEvent(new CustomEvent('site:languagechange', { detail: { language } }));
});

// Mobile menu: closes after a selection or Escape, and resets on desktop.
function closeMenu() {
  nav.classList.remove('is-open');
  menuToggle.setAttribute('aria-expanded', 'false');
  menuToggle.setAttribute('aria-label', language === 'ar' ? 'فتح القائمة' : 'Open menu');
}
menuToggle.addEventListener('click', () => {
  const isOpen = nav.classList.toggle('is-open');
  menuToggle.setAttribute('aria-expanded', String(isOpen));
  menuToggle.setAttribute('aria-label', language === 'ar' ? (isOpen ? 'إغلاق القائمة' : 'فتح القائمة') : (isOpen ? 'Close menu' : 'Open menu'));
});
nav.addEventListener('click', (event) => { if (event.target.closest('a, button')) closeMenu(); });
window.matchMedia('(min-width: 861px)').addEventListener('change', (event) => { if (event.matches) closeMenu(); });
document.addEventListener('keydown', (event) => {
  if (event.key === 'Escape') closeMenu();
  if (!imageDialog.open) return;
  if (event.key === 'ArrowRight') { event.preventDefault(); changeImage(1); }
  if (event.key === 'ArrowLeft') { event.preventDefault(); changeImage(-1); }
});

function openContent(html) {
  if (imageDialog.open) imageDialog.close();
  dialogBody.innerHTML = html;
  document.body.classList.add('modal-open');
  contentDialog.showModal();
}
function contactHTML() {
  return `<a href="mailto:${escapeHTML(SITE_CONFIG.contactEmail)}">${escapeHTML(SITE_CONFIG.contactEmail)}</a>`;
}
function titleHTML(label, title) {
  return `<p class="eyebrow">${label}</p><h2 id="dialog-title">${title}</h2>`;
}
function placeholderHTML(title, frenchText, arabicText) {
  return titleHTML('FARAH EL FASSI', title) + `<p>${language === 'ar' ? arabicText : frenchText}</p>`;
}

const modalBuilders = {
  biographie: () => titleHTML(language === 'ar' ? 'نبذة عني' : 'ABOUT', language === 'ar' ? 'فرح الفاسي' : 'One passion, many worlds.') +
    `<div class="modal-film"><img src="../assets/gallery/img_1605.webp" alt="Portrait of Farah El Fassi"><div><p>${language === 'ar' ? AR.aboutText : $('.about-description').dataset.fr}</p><p>${language === 'ar' ? 'لأي مشروع سينمائي أو تعاون أو طلب إعلامي:' : 'For a creative project, collaboration or media enquiry:'}</p><p>${contactHTML()}</p></div></div>`,
  filmographie: () => titleHTML('CINEMA & TELEVISION', 'Selected roles') +
    `<div class="modal-films">${Object.entries(FILMS).map(([key, film]) => `<button type="button" class="film-card" data-film="${key}"><img src="${film.image}" alt="Poster for ${escapeHTML(film.title)}"><h3>${escapeHTML(film.title)}</h3>${englishFilmTitle(film)}<p>${film.meta}</p></button>`).join('')}</div>`,
  distinctions: () => titleHTML(language === 'ar' ? 'التتويجات' : 'AWARDS', language === 'ar' ? 'مسيرة حافلة بالتتويجات' : 'An award-winning journey') +
    `<ol class="modal-timeline">${AWARDS.map(([year, title, event]) => `<li><time>${year}</time><div><strong>${title}</strong><span>${event}</span></div></li>`).join('')}</ol>`,
  actualites: () => placeholderHTML(language === 'ar' ? 'آخر المستجدات' : 'Latest news',
    'Projects, filming and events: updates will be published here soon.',
    'مشاريع وتصوير ومواعيد: ترقبوا آخر المستجدات قريباً.') +
    `<p><a href="${SITE_CONFIG.social.instagram}" target="_blank" rel="noopener noreferrer">${language === 'ar' ? 'تابعوني على إنستغرام' : 'Follow the latest news on Instagram'} →</a></p>`,
  presse: () => placeholderHTML(language === 'ar' ? 'الصحافة والإعلام' : 'Press & media',
    'For an interview, profile, invitation or any media enquiry, please contact the team.',
    'لإجراء مقابلة أو تقديم دعوة أو لأي طلب إعلامي، يرجى التواصل مع الفريق.') + `<p>${contactHTML()}</p>`,
  video: () => {
    const title = titleHTML(language === 'ar' ? 'العرض الفني' : 'SHOWREEL', language === 'ar' ? 'أدوار، مشاعر، شغف.' : 'Roles, emotions, one shared passion.');
    if (!SITE_CONFIG.showreelVideoUrl) return title + `<p>${language === 'ar' ? 'سيكون العرض الفني متاحاً قريباً. لأي طلب مهني، تواصلوا معنا.' : 'The showreel will be available soon. For professional enquiries, please contact us.'}</p><p>${contactHTML()}</p>`;
    return title + `<video controls playsinline preload="metadata" src="${escapeHTML(SITE_CONFIG.showreelVideoUrl)}">Your browser does not support video playback.</video>`;
  }
};

$$('[data-dialog]').forEach((button) => button.addEventListener('click', () => {
  const builder = modalBuilders[button.dataset.dialog];
  if (builder) openContent(builder());
}));
document.addEventListener('click', (event) => {
  const button = event.target.closest('[data-film]');
  if (!button) return;
  const film = FILMS[button.dataset.film];
  if (!film) return;
  const facts = [['Director', film.director], ['Screenplay', film.writer], ['Running time', film.duration], ['Role', film.role], ['Cast', film.cast]].filter(([, value]) => value);
  openContent(`<div class="modal-film film-detail"><div><img class="film-detail-poster" src="${film.image}" alt="Poster for ${escapeHTML(film.title)}">${film.alternate ? `<details class="film-alternate"><summary>International poster — ${escapeHTML(film.international)}</summary><img src="${film.alternate}" alt="Drowned Heart poster" loading="lazy"></details>` : ''}</div><div>${titleHTML(film.meta, escapeHTML(film.title))}${film.englishTitle ? `<p class="film-english-detail"><span>${escapeHTML(film.englishTitleLabel)}</span>${escapeHTML(film.englishTitle)}</p>` : ''}<p lang="ar" dir="rtl" class="film-arabic">${film.arabic}</p><p>${escapeHTML(film.summary)}</p><dl class="film-facts">${facts.map(([label, value]) => `<div><dt>${label}</dt><dd>${escapeHTML(value)}</dd></div>`).join('')}</dl><p class="film-date-note">${escapeHTML(film.dates)}</p><div class="film-sources"><strong>Find out more</strong>${film.sources.map((source) => `<a href="${source.url}" target="_blank" rel="noopener noreferrer">${escapeHTML(source.label)} ↗</a>`).join('')}</div></div></div>`);
});

// Native dialogs provide focus trapping and Escape handling without a library.
$$('dialog').forEach((dialog) => {
  $('.dialog-close', dialog).addEventListener('click', () => dialog.close());
  dialog.addEventListener('click', (event) => {
    const rect = dialog.getBoundingClientRect();
    if (event.target === dialog && (event.clientX < rect.left || event.clientX > rect.right || event.clientY < rect.top || event.clientY > rect.bottom)) dialog.close();
  });
  dialog.addEventListener('close', () => {
    if (!contentDialog.open && !imageDialog.open) document.body.classList.remove('modal-open');
    $$('video', dialog).forEach((video) => video.pause());
  });
});

// Film row: native touch/trackpad scrolling, arrows and keyboard navigation.
const filmTrack = $('#film-track');
const filmMotion = window.matchMedia('(prefers-reduced-motion: reduce)');
function syncFilmNavigation() {
  const max = Math.max(0, filmTrack.scrollWidth - filmTrack.clientWidth);
  $('[data-film-direction="-1"]').disabled = filmTrack.scrollLeft <= 2;
  $('[data-film-direction="1"]').disabled = filmTrack.scrollLeft >= max - 2;
  $('.film-progress > span').style.width = `${100 * Math.min(1, (filmTrack.scrollLeft + filmTrack.clientWidth) / filmTrack.scrollWidth)}%`;
}
function moveFilms(direction) {
  const card = $('.film-card', filmTrack);
  const stride = card.offsetWidth + parseFloat(getComputedStyle(filmTrack).gap);
  const count = Math.max(1, Math.floor((filmTrack.clientWidth - 50) / stride));
  filmTrack.scrollBy({ left: direction * count * stride, behavior: filmMotion.matches ? 'instant' : 'smooth' });
}
$$('[data-film-direction]').forEach((button) => button.addEventListener('click', () => moveFilms(Number(button.dataset.filmDirection))));
filmTrack?.addEventListener('scroll', syncFilmNavigation, { passive: true });
filmTrack?.addEventListener('keydown', (event) => {
  if (event.target !== filmTrack || !['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return;
  event.preventDefault();
  if (event.key === 'Home' || event.key === 'End') filmTrack.scrollTo({ left: event.key === 'Home' ? 0 : filmTrack.scrollWidth, behavior: filmMotion.matches ? 'instant' : 'smooth' });
  else moveFilms(event.key === 'ArrowRight' ? 1 : -1);
});
if (filmTrack) {
  new ResizeObserver(syncFilmNavigation).observe(filmTrack);
  syncFilmNavigation();
}

// Cinematic gallery: shared selection for the stage, thumbnails and lightbox.
function visibleGallery() { return $$('.gallery-item', track).filter((item) => !item.hidden); }
const gallery = $('#galerie');
const galleryMotion = window.matchMedia('(prefers-reduced-motion: reduce)');
const categoryNames = { portraits: 'Portraits', events: 'Events', sets: 'On set', life: 'Everyday moments', press: 'Press' };
let galleryPlaying = !galleryMotion.matches;
let galleryInView = false;
let galleryHover = false;
let galleryTimer;
let galleryRequest = 0;
function syncGalleryPlayback() {
  clearTimeout(galleryTimer);
  if (!$('#cinema-play')) return;
  const playing = galleryPlaying && !galleryMotion.matches;
  $('#cinema-play img').src = `../assets/icons/${playing ? 'pause' : 'play'}.svg`;
  $('#cinema-play').setAttribute('aria-pressed', String(playing));
  $('#cinema-play').setAttribute('aria-label', playing ? 'Pause slideshow' : 'Play slideshow');
  if (playing && galleryInView && !galleryHover && !document.hidden && !imageDialog.open && !gallery.contains(document.activeElement) && visibleGallery().length > 1) {
    galleryTimer = window.setTimeout(() => selectGallery(currentImageIndex + 1), 6500);
  }
}
async function selectGallery(index, manual = false) {
  if (!$('#cinema-photo')) return;
  const items = visibleGallery();
  if (!items.length) return;
  currentImageIndex = (index + items.length) % items.length;
  const item = items[currentImageIndex];
  const request = ++galleryRequest;
  $$('.gallery-item', track).forEach((thumb) => {
    thumb.classList.toggle('is-current', thumb === item);
    thumb.setAttribute('aria-pressed', String(thumb === item));
  });
  $('#cinema-caption').textContent = item.dataset.caption;
  $('#cinema-caption').dataset.length = item.dataset.caption.length > 28 ? 'long' : 'normal';
  $('#cinema-category').textContent = categoryNames[item.dataset.category];
  $('#cinema-counter').innerHTML = `${String(currentImageIndex + 1).padStart(2, '0')} <span>/ ${String(items.length).padStart(2, '0')}</span>`;
  $('.cinema-progress span').style.width = `${100 * (currentImageIndex + 1) / items.length}%`;
  const left = item.offsetLeft - (track.clientWidth - item.clientWidth) / 2;
  track.scrollTo({ left, behavior: manual && !galleryMotion.matches ? 'smooth' : 'auto' });
  $$('[data-gallery-direction]').forEach((button) => { button.disabled = items.length < 2; });
  if (manual) $('#cinema-status').textContent = `${item.dataset.caption}, photo ${currentImageIndex + 1} of ${items.length}`;
  const preload = new Image();
  preload.src = item.dataset.image;
  try { await preload.decode(); } catch { /* Keep navigation usable if an image fails. */ }
  if (request !== galleryRequest) return;
  const photo = $('#cinema-photo');
  $('.cinema-stage').classList.toggle('is-landscape', preload.naturalWidth > preload.naturalHeight);
  $('.cinema-stage').classList.toggle('is-rotated', item.dataset.rotation === '-90');
  photo.style.objectPosition = item.dataset.rotation ? '50% 50%' : (item.dataset.position || '50% 18%');
  photo.src = item.dataset.image;
  photo.alt = item.dataset.caption;
  $('.cinema-backdrop').src = $('img', item).src;
  if (!galleryMotion.matches) {
    photo.getAnimations().forEach((animation) => animation.cancel());
    photo.animate([{ opacity: .25, transform: 'scale(1.025)' }, { opacity: 1, transform: 'scale(1)' }], { duration: 900, easing: 'cubic-bezier(.2,.6,.2,1)' });
  }
  syncGalleryPlayback();
}
$$('[data-filter]').forEach((button) => button.addEventListener('click', () => {
  $$('[data-filter]').forEach((other) => {
    other.classList.toggle('is-active', other === button);
    other.setAttribute('aria-pressed', String(other === button));
  });
  $$('.gallery-item', track).forEach((item) => { item.hidden = button.dataset.filter !== 'all' && item.dataset.category !== button.dataset.filter; });
  selectGallery(0, true);
}));
$$('[data-gallery-direction]').forEach((button) => button.addEventListener('click', () => selectGallery(currentImageIndex + Number(button.dataset.galleryDirection), true)));
$$('.gallery-item', track).forEach((item) => item.addEventListener('click', () => {
  const index = visibleGallery().indexOf(item);
  if ($('#cinema-photo')) selectGallery(index, true);
  else {
    currentImageIndex = index;
    renderLightbox();
    document.body.classList.add('modal-open');
    imageDialog.showModal();
  }
}));
$('#cinema-play')?.addEventListener('click', () => { galleryPlaying = !galleryPlaying; syncGalleryPlayback(); });
function renderLightbox() {
  const items = visibleGallery();
  currentImageIndex = (currentImageIndex + items.length) % items.length;
  const item = items[currentImageIndex];
  $('#lightbox-image').classList.toggle('is-rotated', item.dataset.rotation === '-90');
  $('#lightbox-image').src = item.dataset.image;
  $('#lightbox-image').alt = item.dataset.caption;
  $('#image-caption').textContent = `${item.dataset.caption} · ${currentImageIndex + 1} / ${items.length}`;
  $$('[data-lightbox-direction]').forEach((button) => { button.hidden = items.length < 2; });
}
function changeImage(direction) { currentImageIndex += direction; renderLightbox(); selectGallery(currentImageIndex); }
$$('[data-gallery-expand]').forEach((button) => button.addEventListener('click', () => {
  renderLightbox();
  document.body.classList.add('modal-open');
  imageDialog.showModal();
  syncGalleryPlayback();
}));
$$('[data-lightbox-direction]').forEach((button) => button.addEventListener('click', () => changeImage(Number(button.dataset.lightboxDirection))));
imageDialog.addEventListener('close', syncGalleryPlayback);
gallery?.addEventListener('keydown', (event) => {
  if (!$('#cinema-photo')) return;
  if (imageDialog.open || !['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return;
  event.preventDefault();
  selectGallery(event.key === 'Home' ? 0 : event.key === 'End' ? visibleGallery().length - 1 : currentImageIndex + (event.key === 'ArrowRight' ? 1 : -1), true);
});
let touchStart;
$('.cinema-stage')?.addEventListener('touchstart', (event) => { touchStart = [event.touches[0].clientX, event.touches[0].clientY]; }, { passive: true });
$('.cinema-stage')?.addEventListener('touchend', (event) => {
  if (!touchStart) return;
  const dx = event.changedTouches[0].clientX - touchStart[0];
  const dy = event.changedTouches[0].clientY - touchStart[1];
  if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy) * 1.5) selectGallery(currentImageIndex + (dx < 0 ? 1 : -1), true);
  touchStart = null;
}, { passive: true });
gallery?.addEventListener('mouseenter', () => { galleryHover = true; syncGalleryPlayback(); });
gallery?.addEventListener('mouseleave', () => { galleryHover = false; syncGalleryPlayback(); });
gallery?.addEventListener('focusin', syncGalleryPlayback);
gallery?.addEventListener('focusout', () => window.setTimeout(syncGalleryPlayback, 0));
document.addEventListener('visibilitychange', syncGalleryPlayback);
galleryMotion.addEventListener('change', () => { galleryPlaying = !galleryMotion.matches; syncGalleryPlayback(); });
if (gallery) new IntersectionObserver(([entry]) => { galleryInView = entry.isIntersecting; syncGalleryPlayback(); }, { threshold: .15 }).observe(gallery);
selectGallery(Math.max(0, visibleGallery().findIndex((item) => item.dataset.image.endsWith('img_2830.webp'))));

// Underline the visible section without overriding the user’s hash history.
const sections = ['accueil', 'a-propos', 'filmographie', 'galerie', 'contact'].map((id) => document.getElementById(id)).filter(Boolean);
let scrollQueued = false;
function updateNavigation() {
  if (document.body.dataset.page) { scrollQueued = false; return; }
  const threshold = window.innerHeight * .25;
  let active = 'accueil';
  for (const section of sections) if (section.getBoundingClientRect().top <= threshold) active = section.id;
  $$('.main-nav a[href^="#"]').forEach((link) => {
    const current = link.getAttribute('href') === `#${active}`;
    link.classList.toggle('is-active', current);
    if (current) link.setAttribute('aria-current', 'location'); else link.removeAttribute('aria-current');
  });
  scrollQueued = false;
}
window.addEventListener('scroll', () => { if (!scrollQueued) { scrollQueued = true; requestAnimationFrame(updateNavigation); } }, { passive: true });
updateNavigation();

function englishFilmTitle(film) {
  return film.englishTitle ? `<span class="film-english-title">${escapeHTML(film.englishTitle)}</span>` : '';
}
