'use strict';

// Page-specific translations extend the shared navigation and dialog vocabulary.
Object.assign(AR, {
  profileTitle: 'شغف،<br>أدوار،<br>وحكاية.',
  profileIntro: 'بين السينما والتلفزيون، أعيش حكايات تشبه حياتنا. مسيرتي مغامرة إنسانية، تصنعها اللقاءات والمشاعر وحب عميق لمهنتي.',
  profileJourney: 'اكتشفوا مسيرتي',
  profileRoleQuote: 'كل دور لقاء،<br>وكل حكاية جزء مني.',
  profileDisciplines: 'سينما<br>تلفزيون<br>ثقافة<br>مجتمع<br>التزام',
  profileBiography: 'سيرتي',
  profileBioTitle: 'فنانة تستلهم<br>الإنسان',
  profileBioOne: 'فرح الفاسي ممثلة مغربية أسرت موهبتها وحساسيتها الجمهور في المغرب وخارجه. ومن خلال أدوار بارزة في التلفزيون والسينما، رسخت حضورها في المشهد الفني المغربي.',
  profileBioTwo: 'بعيداً عن الأدوار، فرح امرأة صاحبة قناعات وقريبة من جمهورها، تؤمن بالأصالة والاحترام والمشاركة. وتعكس مسيرتها قوة جيل يرى في الثقافة وسيلة للحوار والتغيير.',
  profileBioMore: 'على مدى عشرين سنة، تغتني مسيرتها باللقاءات والشخصيات المتنوعة. من أفراح صغيرة إلى آخر اختيار، مروراً بالصفحة الأولى وبين القصور، تستكشف العلاقات والاختيارات والمشاعر التي تعبر حياتنا.',
  profileHumanQuote: 'أؤمن بحكايات تجمعنا،<br>وتلهمنا وتترك أثراً إيجابياً.',
  profileMilestones: 'محطات بارزة',
  profileJourneyTitle: 'مسيرة<br>في حركة مستمرة',
  profilePassion: 'شغف واحد',
  profilePassionText: 'حكايات ولقاءات تمنحنا فرصة للنمو.',
  profileSmallJoys: 'حكاية صداقة على الشاشة الكبيرة.',
  profileFirstPage: 'نظرة إلى المجتمع عبر التلفزيون.',
  profileTwoWorlds: 'سينما وتلفزيون',
  profileToday: 'اليوم',
  profileFurther: 'نحو آفاق جديدة',
  profileFurtherText: 'مشاريع جديدة،<br>والشغف نفسه.',
  profileAwardsTitle: 'موهبة<br>متوجة',
  profileAwardsText: 'هذه التتويجات اعتراف جميل، لكن أكبر مكافأة لي تبقى ثقة الجمهور وحبه.',
  profileAwardsQuote: 'تشجعني هذه التتويجات على المضي قدماً والدفاع عن حكايات تحمل معنى.',
  profileValues: 'قيمي',
  profileValuesTitle: 'التزام<br>يتجاوز الشاشات',
  profileArtQuote: 'الفن أقوى<br>حين يخدم الإنسان.',
  profileValuesText: 'أؤمن بقوة الثقافة في تقريب الناس وتشجيع الحوار وبناء مجتمع أكثر تضامناً. ومن خلال اختياراتي الفنية والتزاماتي، أرغب في تسليط الضوء على حكايات مهمة ودعم قضايا قريبة من قلبي، ومنها التعليم وحقوق النساء وإتاحة الثقافة للجميع.',
  profileCommitment: 'التزامي',
  profileGallery: 'معرض الصور',
  profilePortraits: 'بورتريهات فنانة',
  profileAllGallery: 'شاهدوا كل الصور'
});
